name: Creating Jira
on: [pull_request]
jobs:
  test-create-issue:
    name: Create Issue
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: https://amankmr1207.atlassian.net
        JIRA_USER_EMAIL: amankmr1207@gmail.com
        JIRA_API_TOKEN: ${{ secrets.JIRA }}

    - name: Create
      id: create
      uses: atlassian/gajira-create@master
      with:
        project: Dependency
        issuetype: Task
        summary: |
          Dependency scan result
        description: |
          Dependency Scan for pull request https://github.com/${{ github.repository }}/pull/${{github.event.number}}
        fields: '{"assignee": {"name":"amankmr1207@gmail.com"}}'
        
    - name: Transition issue
      uses: atlassian/gajira-transition@master
      with:
        issue: ${{ steps.create.outputs.issue }}
        transition: "In progress"
        
    - name: Log created issue
      run: echo "Issue ${{ steps.create.outputs.issue }} was created"
